In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame({"Name":["Aman","Saurav","Karan","Subham","abhishek","none","Sammer"],
                 "Age":[22,23,np.nan,22,25,24,26],
                 "Marks":[90,85,88,92,95,np.nan,80],
                 "Subject":["Maths","Science","English","Hindi","History","Geography","Chemistry"]})
df

       Name   Age  Marks    Subject
0      Aman  22.0   90.0      Maths
1    Saurav  23.0   85.0    Science
2     Karan   NaN   88.0    English
3    Subham  22.0   92.0      Hindi
4  abhishek  25.0   95.0    History
5      none  24.0    NaN  Geography
6    Sammer  26.0   80.0  Chemistry

In [4]:
df.shape

(7, 4)

In [5]:
df.dtypes

Name           str
Age        float64
Marks      float64
Subject        str
dtype: object

In [6]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   23.666667  88.333333
std     1.632993   5.316641
min    22.000000  80.000000
25%    22.250000  85.750000
50%    23.500000  89.000000
75%    24.750000  91.500000
max    26.000000  95.000000

In [7]:
df[["Name","Subject"]]

       Name    Subject
0      Aman      Maths
1    Saurav    Science
2     Karan    English
3    Subham      Hindi
4  abhishek    History
5      none  Geography
6    Sammer  Chemistry

In [8]:
df[df['Marks']>85]

       Name   Age  Marks  Subject
0      Aman  22.0   90.0    Maths
2     Karan   NaN   88.0  English
3    Subham  22.0   92.0    Hindi
4  abhishek  25.0   95.0  History

In [9]:
df[(df['Age']>22) & (df['Marks']>85)]

       Name   Age  Marks  Subject
4  abhishek  25.0   95.0  History

In [10]:
df.groupby("Subject")["Marks"].count()

Subject
Chemistry    1
English      1
Geography    0
Hindi        1
History      1
Maths        1
Science      1
Name: Marks, dtype: int64

In [11]:
df.sort_values("Marks",ascending=False)

       Name   Age  Marks    Subject
4  abhishek  25.0   95.0    History
3    Subham  22.0   92.0      Hindi
0      Aman  22.0   90.0      Maths
2     Karan   NaN   88.0    English
1    Saurav  23.0   85.0    Science
6    Sammer  26.0   80.0  Chemistry
5      none  24.0    NaN  Geography

In [12]:
df.nlargest(2,"Marks")

       Name   Age  Marks  Subject
4  abhishek  25.0   95.0  History
3    Subham  22.0   92.0    Hindi

In [13]:
df.nsmallest(1,"Marks")

     Name   Age  Marks    Subject
6  Sammer  26.0   80.0  Chemistry

In [14]:
df.isna().sum()

Name       0
Age        1
Marks      1
Subject    0
dtype: int64

In [15]:
df[df['Marks'].isna()]

   Name   Age  Marks    Subject
5  none  24.0    NaN  Geography

In [16]:
cleaned_df=df.dropna()

In [17]:
df.shape

(7, 4)

In [18]:
cleaned_df.shape

(5, 4)

1.if pandas found some missing value in data so it will automatically converts the entire coulumn to float type...

2.using inplace=true leads to permanently modifies the original dataframe.

3.a.do not allow empty or null value.
  b.avoid extra space,symbols and number.